
### Create Stages Batch
POST http://127.0.0.1:5000/stages/v1/create_stages_batch
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjM2Njk4NDh9.vKXRTn5f1y53ti-SMjNvMUJ5_KE998bYZ-oxyYDBkkc

{
    "stages": [
        {
            "id_project": 1,
            "name": "Etapa 1",
            "description": "Descripción de la etapa 1",
            "start_date": "2025-10-15T09:00:00",
            "end_date": "2025-11-01T18:00:00",
            "coverage_request": "MATERIALES",
            "requires_contribution": true
        },
        {
            "id_project": 1,
            "name": "Etapa 2",
            "description": "Descripción de la etapa 2",
            "start_date": "2025-11-02T09:00:00",
            "end_date": "2025-11-20T18:00:00",
            "coverage_request": "MATERIALES",
            "requires_contribution": true
        }
    ]
}




### wwww
POST http://127.0.0.1:5000/login/v1/authenticate
Content-Type: application/json

{
    "email": "ong_colaborativa@projectplanning.org",
    "password": "ong_colaborativa"
}



### Get All Available Stages
GET http://127.0.0.1:5000/stages/v1/get_all_available_stages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjM2Njk4NDh9.vKXRTn5f1y53ti-SMjNvMUJ5_KE998bYZ-oxyYDBkkc



### cover_stages
PATCH http://127.0.0.1:5000/stages/v1/cover_stage/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3NjM2NzAxNTN9.8tDnPG01LGfRW1GXIh7Abghfqk3B3hUBxfg4NIGIVVk
